CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL
  password VARCHAR(255) NOT NULL
);

CREATE TABLE userdata (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  user_name VARCHAR(255) NOT NULL,
  user_occupation VARCHAR(255) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);